name: My first

on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
          
        - name: Welcome Message
          run: echo 'Hello world Welcome to git hub actions'
          
        - name: list
          run: ls
